# Generated by Django 5.0.7 on 2024-07-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='tags',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
