# Generated by Django 5.0.7 on 2024-08-09 09:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments_created_at_comments_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followings',
            unique_together={('follower', 'following')},
        ),
    ]
